# Generated by Django 3.0.8 on 2020-08-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idcarrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('nombrecorto', models.TextField()),
                ('fecha_fundacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
