# Generated by Django 3.0.8 on 2020-08-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('dni', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
